<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="SVPKHOME" failures="1" tests="4" name="Verify Login" time="14.959" errors="0" timestamp="2022-12-30T03:42:14 IST">
  <testcase classname="com.bpp.testCases.VerifyLogin" name="verifyLogin" time="1.22">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Login error alert message mismatch expected [These credentials do not match our records.] but found [The username field is required.]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Login error alert message mismatch expected [These credentials do not match our records.] but found [The username field is required.]
at com.bpp.testCases.VerifyLogin.verifyLogin(VerifyLogin.java:123)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- verifyLogin -->
  <testcase classname="com.bpp.testCases.VerifyLogin" name="verifyLogin" time="2.739"/>
  <testcase classname="com.bpp.testCases.VerifyLogin" name="verifyLogin" time="2.1"/>
  <testcase classname="com.bpp.testCases.VerifyLogin" name="verifyLogin" time="2.781"/>
  <testcase classname="com.bpp.testCases.VerifyLogin" name="login" time="0.0">
    <ignored/>
  </testcase> <!-- login -->
</testsuite> <!-- Verify Login -->
